# Site settings
title: Gallop Lab
description: 
baseurl: "/gallop-lab.github.io/" # the subpath of your site, e.g. /blog/
url: "https://gallob.group/" # the base hostname & protocol for your site
twitter_username: galloplab

# Build settings
markdown: kramdown
